# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c128e8b5312f2d5908f6c6b728bea647e53c19c76adca46896570ae6fac47f3222a01533424edbe887802c302b5175e3f735855222eb72f0aba42fdc71a61dfe

test:
  secret_key_base: 06d955576d79f138ca5aa7113348ce271b683bb3a4d38061de581b15e4983b3ee0804f54e04395b26fa7a8d94e581ee05880beb54d0f7ea2d77b6eaaf0e1f23b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
